spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs   # OpenAPI 3.x 문서의 기본 경로
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # Swagger UI 경로

